language: csharp
dist: trusty
mono: none
dotnet: 2.1
install:
- dotnet restore
script:
- dotnet build NotesCore/NotesCore.csproj
- dotnet test NoteTests/NoteTests.csproj
- npm install NotesCore/clientapp
- npm run build NotesCore/clientapp
